# Generated by Django 5.0.6 on 2024-05-16 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='data',
        ),
        migrations.AddField(
            model_name='todolist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
